using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Dotnet
{
     
    public class KeyAttribute:ColumnAttribute
    {
        public KeyAttribute()
        {
        }
        public KeyAttribute(string columnName):base(columnName)
        {
        }

        private bool isAutoGenerated = false;

        /// <summary>
        /// 是否是自增列
        /// </summary>
        public bool IsAutoGenerated
        {
            get
            {
                return this.isAutoGenerated;
            }
            set
            {
                this.isAutoGenerated = value;
            }
        }
    }
}
